---
title: "wk4-workshop"
author: "kenwan cheung"
date: "4/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
probabilities<-c(.1,.3,.5,.05,.05)
sum(probabilities)

init<-2

oneStep<-function(initSt,probabilities){
  numberStates<-length(probabilities)
  turn<-sample(c(-1,1),1)
  newStates<-c(init, init+turn)
  if (newStates[2]==numberStates+1) newStates[2]<-1
  if (newStates[2]==0) newStates[2]<-numberStates
  if (probabilities[newStates[2]]>probabilities[newStates[1]]) { 
    res<-newStates[2]
  } else {  
    p<-probabilities[newStates[2]]/probabilities[newStates[1]]
    res<-sample(newStates,1,prob = c(1-p,p))
  }  
  res
}  

trajectory<-rep(NA,100000)
for (i in 1:100000){
init<-oneStep(init,probabilities)
trajectory[i]<-init
} 
table(trajectory)

```

jags

```{r}

# install.packages("rjags")
library(rjags)

dataPath = "/Users/kenwancheung/Documents/msca/bayesian/"

suppressWarnings(source(paste(dataPath,"DBDA2Eprograms/DBDA2E-utilities.R",sep="/")))

myData<-read.csv(paste(dataPath,"wk4/z15N50.csv",sep="/"))
head(myData)

```

Next

```{r}

y<-myData$y
(Ntotal<-length(y))

(dataList<-list(y=y,Ntotal=Ntotal))

```